export const documentConfigs = {
  invoice: {
    buttonText: 'Save Bill',
    dateLabel: 'Invoice Date',
    documentType: 'gst-invoice',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Bill To',
    prefix: 'INV',
    showDueDate: true,
    showGst: true,
    showPayment: true,
    title: 'GST Invoice',
  },
  quotation: {
    buttonText: 'Create Quotation',
    dateLabel: 'Quote Date',
    documentType: 'quotation',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Quote To',
    prefix: 'QTN',
    showGst: false,
    showPayment: false,
    showValidTill: true,
    title: 'Quotation',
  },
  proforma: {
    buttonText: 'Create Proforma Invoice',
    dateLabel: 'Invoice Date',
    documentType: 'proforma-invoice',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Bill To',
    prefix: 'PFI',
    showDueDate: true,
    showGst: true,
    showPayment: false,
    title: 'Proforma Invoice',
  },
  'purchase-order': {
    buttonText: 'Create Purchase Order',
    dateLabel: 'PO Date',
    documentType: 'purchase-order',
    partyNameLabel: 'Vendor / Supplier Name *',
    partyToLabel: 'Vendor',
    prefix: 'PO',
    showDeliveryAddress: true,
    showExpectedDelivery: true,
    showGst: true,
    showPayment: false,
    title: 'Purchase Order',
  },
  'credit-note': {
    buttonText: 'Create Credit Note',
    dateLabel: 'Credit Note Date',
    documentType: 'credit-note',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Bill To',
    prefix: 'CRN',
    reasonLabel: 'Reason for Credit',
    showGst: true,
    showOriginalRef: true,
    showPayment: true,
    title: 'Credit Note',
  },
  'debit-note': {
    buttonText: 'Create Debit Note',
    dateLabel: 'Debit Note Date',
    documentType: 'debit-note',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Bill To',
    prefix: 'DBN',
    reasonLabel: 'Reason for Debit',
    showGst: true,
    showOriginalRef: true,
    showPayment: true,
    title: 'Debit Note',
  },
  'delivery-challan': {
    buttonText: 'Create Delivery Challan',
    dateLabel: 'Challan Date',
    documentType: 'delivery-challan',
    partyNameLabel: 'Consignee / Company Name *',
    partyToLabel: 'Consignee',
    prefix: 'DC',
    showGst: false,
    showPayment: false,
    showTransport: true,
    title: 'Delivery Challan',
  },
  'e-invoice': {
    buttonText: 'Generate E-Invoice',
    dateLabel: 'Invoice Date',
    documentType: 'e-invoice',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Bill To',
    prefix: 'EI',
    showDueDate: true,
    showGst: true,
    showIRN: true,
    showPayment: true,
    title: 'E-Invoice',
  },
  'e-way-bill': {
    buttonText: 'Generate E-Way Bill',
    dateLabel: 'Date',
    documentType: 'e-way-bill',
    partyNameLabel: 'Consignee / Company Name *',
    partyToLabel: 'Consignee',
    prefix: 'EWB',
    showEWayBillFields: true,
    showGst: true,
    showPayment: false,
    showTransport: true,
    title: 'E-Way Bill',
  },
};
