const MONEY = new Intl.NumberFormat('en-IN', {
  style: 'currency',
  currency: 'INR',
  maximumFractionDigits: 0,
});

function money(value) {
  return MONEY.format(value);
}

const CATEGORY_DASHBOARDS = {
  retail: {
    title: 'Retail Store Dashboard',
    subtitle: 'Track sales, purchases, stock movement, and receivables.',
    primaryChartTitle: 'Weekly Sales',
    donutTitle: 'Collection Status',
    listTitle: 'Top Selling Products',
    secondaryCardTitle: 'Store Operations',
    inventoryTitle: 'Stock Snapshot',
    scoreTitle: 'Store Health Score',
    metrics: [
      { label: 'Today Sales', value: money(128400), trend: '+12% vs yesterday', hash: '/dashboard' },
      { label: 'Purchase Value', value: money(74200), trend: '5 purchase entries', hash: '/reports' },
      { label: 'Receivables', value: money(46800), trend: '8 invoices pending', hash: '/billing/receivables' },
      { label: 'Low Stock Items', value: '14', trend: '4 need reorder', hash: '/stock-alerts' },
    ],
    trend: [
      { label: 'Mon', total: 82000 }, { label: 'Tue', total: 94000 }, { label: 'Wed', total: 88000 },
      { label: 'Thu', total: 112000 }, { label: 'Fri', total: 128400 },
    ],
    donut: { paid: 81600, pending: 32400, overdue: 14400 },
    list: [
      { name: 'Premium Rice 25kg', total: 42 },
      { name: 'Sunflower Oil 5L', total: 31 },
      { name: 'Household Combo', total: 24 },
    ],
    secondary: [
      { label: 'Bills today', value: 38, color: '#2563eb', bg: '#eff6ff' },
      { label: 'Purchase entries', value: 5, color: '#16a34a', bg: '#f0fdf4' },
      { label: 'Returns', value: 3, color: '#d97706', bg: '#fffbeb' },
      { label: 'Stock alerts', value: 14, color: '#be123c', bg: '#fff1f2' },
    ],
    inventory: { total: 486, inStock: 438, lowStock: 34, outOfStock: 14 },
    score: { score: 82, growthPct: 9 },
  },
  school: {
    title: 'School Dashboard',
    subtitle: 'A consolidated overview of students, attendance, fees, academics, and operations.',
    primaryChartTitle: 'Attendance Trend',
    donutTitle: 'Fee Collection Status',
    listTitle: 'Class Strength',
    secondaryCardTitle: "Today's Overview",
    inventoryTitle: 'Student Overview',
    scoreTitle: 'School Performance Score',
    metrics: [
      { label: 'Total Students', value: '1,248', trend: '1,174 active', hash: '/school/students/list' },
      { label: 'Active Students', value: '1,174', trend: '94% of total', hash: '/school/students/list' },
      { label: 'New Admissions', value: '32', trend: 'this month', hash: '/school/admissions/new-admission' },
      { label: 'Total Teachers/Staff', value: '68', trend: 'across all departments', hash: '/school/academics/teachers-subjects' },
      { label: "Today's Fee Collection", value: money(48000), trend: '86% of due today', hash: '/school/fees/collect-fees' },
      { label: 'Total Outstanding Fees', value: money(118000), trend: '92 students pending', hash: '/school/fees/outstanding' },
    ],
    trend: [
      { label: 'Mon', total: 92 }, { label: 'Tue', total: 94 }, { label: 'Wed', total: 93 },
      { label: 'Thu', total: 95 }, { label: 'Fri', total: 94 },
    ],
    donut: { paid: 684000, pending: 92000, overdue: 26000 },
    list: [
      { name: 'Grade 10', total: 186 },
      { name: 'Grade 9', total: 174 },
      { name: 'Grade 8', total: 168 },
    ],
    secondary: [
      { label: "Today's Attendance", value: '94%', color: '#2563eb', bg: '#eff6ff' },
      { label: 'Absent Students', value: 58, color: '#dc2626', bg: '#fef2f2' },
      { label: 'Late Students', value: 16, color: '#d97706', bg: '#fffbeb' },
      { label: 'Upcoming Examinations', value: 6, color: '#7c3aed', bg: '#f5f3ff' },
      { label: 'Pending Homework', value: 24, color: '#d97706', bg: '#fffbeb' },
      { label: 'Recent Notices', value: '3 new', color: '#2563eb', bg: '#eff6ff' },
      { label: 'Transport Status', value: '18 routes on time', color: '#16a34a', bg: '#f0fdf4' },
      { label: 'Library Activity', value: '42 issued today', color: '#16a34a', bg: '#f0fdf4' },
    ],
    inventory: { total: 1248, inStock: 1174, lowStock: 52, outOfStock: 22 },
    score: { score: 89, growthPct: 6 },
    quickActions: [
      { label: 'New Admission', route: '/school/admissions/new-admission' },
      { label: 'View Applications', route: '/school/admissions/applications' },
      { label: 'Mark Attendance', route: '/school/attendance/student-attendance' },
      { label: 'Collect Fees', route: '/school/fees/collect-fees' },
      { label: 'Enter Marks', route: '/school/examinations/marks-entry' },
      { label: 'Create Homework', route: '/school/homework/create' },
      { label: 'Add Notice', route: '/school/communication/notices' },
    ],
  },
  hospital: {
    title: 'Hospital Dashboard',
    subtitle: 'Track patients, appointments, admissions, pharmacy, and billing.',
    primaryChartTitle: 'Patient Visits',
    donutTitle: 'Billing Status',
    listTitle: 'Department Load',
    secondaryCardTitle: 'Clinical Operations',
    inventoryTitle: 'Pharmacy Snapshot',
    scoreTitle: 'Hospital Service Score',
    metrics: [
      { label: 'Patients Today', value: '186', trend: '42 new registrations', hash: '/hospital/patients' },
      { label: 'Appointments', value: '74', trend: '18 waiting', hash: '/hospital/appointments' },
      { label: 'Admissions', value: '28', trend: '6 discharges today', hash: '/hospital/admissions' },
      { label: 'Revenue', value: money(526000), trend: '+8% vs yesterday', hash: '/hospital/revenue-reports' },
    ],
    trend: [
      { label: 'Mon', total: 142 }, { label: 'Tue', total: 158 }, { label: 'Wed', total: 166 },
      { label: 'Thu', total: 174 }, { label: 'Fri', total: 186 },
    ],
    donut: { paid: 368000, pending: 112000, overdue: 46000 },
    list: [
      { name: 'General Medicine', total: 48 },
      { name: 'Orthopaedics', total: 34 },
      { name: 'Paediatrics', total: 29 },
    ],
    secondary: [
      { label: 'Doctors on duty', value: 26, color: '#2563eb', bg: '#eff6ff' },
      { label: 'Beds available', value: 42, color: '#16a34a', bg: '#f0fdf4' },
      { label: 'Lab reports pending', value: 18, color: '#d97706', bg: '#fffbeb' },
      { label: 'Claims pending', value: 11, color: '#7c3aed', bg: '#f5f3ff' },
    ],
    inventory: { total: 862, inStock: 738, lowStock: 86, outOfStock: 38 },
    score: { score: 86, growthPct: 7 },
  },
  manufacturing: {
    title: 'Manufacturing Dashboard',
    subtitle: 'Monitor production, quality, materials, downtime, and dispatch.',
    primaryChartTitle: 'Production Output',
    donutTitle: 'Order Status',
    listTitle: 'Production Lines',
    secondaryCardTitle: 'Factory Operations',
    inventoryTitle: 'Material Snapshot',
    scoreTitle: 'Production Efficiency Score',
    metrics: [
      { label: 'Production Today', value: '4,280', trend: '94% of target', hash: '/dashboard' },
      { label: 'Active Work Orders', value: '18', trend: '6 due this week', hash: '/dashboard' },
      { label: 'Quality Rejections', value: '2.4%', trend: '-0.6% this month', hash: '/dashboard' },
      { label: 'Machine Downtime', value: '3.2h', trend: '2 machines affected', hash: '/dashboard' },
    ],
    trend: [
      { label: 'Mon', total: 3880 }, { label: 'Tue', total: 4120 }, { label: 'Wed', total: 4040 },
      { label: 'Thu', total: 4210 }, { label: 'Fri', total: 4280 },
    ],
    donut: { paid: 62, pending: 26, overdue: 12 },
    list: [
      { name: 'Assembly Line A', total: 96 },
      { name: 'Assembly Line B', total: 91 },
      { name: 'Packaging Line', total: 88 },
    ],
    secondary: [
      { label: 'Work orders', value: 18, color: '#2563eb', bg: '#eff6ff' },
      { label: 'Lines running', value: 7, color: '#16a34a', bg: '#f0fdf4' },
      { label: 'Quality holds', value: 4, color: '#d97706', bg: '#fffbeb' },
      { label: 'Maintenance jobs', value: 6, color: '#7c3aed', bg: '#f5f3ff' },
    ],
    inventory: { total: 742, inStock: 628, lowStock: 82, outOfStock: 32 },
    score: { score: 84, growthPct: 8 },
  },  hotel: {
    title: 'Hotel Dashboard',
    subtitle: "Here's the current snapshot of occupancy, arrivals, departures, and revenue.",
    primaryChartTitle: 'Occupancy Trend',
    donutTitle: 'Room Revenue Mix',
    listTitle: 'Today At A Glance',
    secondaryCardTitle: 'ADR / RevPAR',
    inventoryTitle: 'Room Inventory',
    scoreTitle: 'Service Health Score',
    metrics: [
      { label: 'Occupancy %', value: '78%', trend: '+6% vs yesterday', hash: '/hotel/dashboard/occupancy' },
      { label: "Today's Arrivals", value: '24', trend: '8 VIP arrivals', hash: '/hotel/dashboard/arrivals' },
      { label: "Today's Departures", value: '18', trend: '12 checked out', hash: '/hotel/dashboard/departures' },
      { label: 'Revenue', value: money(486000), trend: '+12% vs last week', hash: '/hotel/dashboard/revenue' },
      { label: 'ADR / RevPAR', value: `${money(6200)} / ${money(4836)}`, trend: 'ADR up 4%', hash: '/hotel/dashboard/adr-revpar' },
    ],
    trend: [
      { label: 'Mon', total: 68 }, { label: 'Tue', total: 72 }, { label: 'Wed', total: 75 },
      { label: 'Thu', total: 78 }, { label: 'Fri', total: 84 }, { label: 'Sat', total: 91 }, { label: 'Sun', total: 78 },
    ],
    donut: { paid: 286000, pending: 138000, overdue: 62000 },
    list: [
      { name: 'Checked-in guests', total: 112 },
      { name: 'Rooms available', total: 32 },
      { name: 'Housekeeping pending', total: 14 },
    ],
    secondary: [
      { label: 'ADR', value: money(6200), color: '#2563eb', bg: '#eff6ff' },
      { label: 'RevPAR', value: money(4836), color: '#16a34a', bg: '#f0fdf4' },
      { label: 'Room revenue', value: money(392000), color: '#7c3aed', bg: '#f5f3ff' },
      { label: 'F&B revenue', value: money(94000), color: '#d97706', bg: '#fffbeb' },
    ],
    inventory: { total: 148, inStock: 116, lowStock: 18, outOfStock: 14 },
    score: { score: 84, growthPct: 7 },
  },
  construction: {
    title: 'Construction Dashboard',
    subtitle: 'Track active projects, site progress, material cost, and pending bills.',
    primaryChartTitle: 'Site Progress',
    donutTitle: 'Pending Bills Split',
    listTitle: 'Active Projects',
    secondaryCardTitle: 'Project Controls',
    inventoryTitle: 'Materials Snapshot',
    scoreTitle: 'Execution Score',
    metrics: [
      { label: 'Active Projects', value: '12', trend: '4 high priority', hash: '/construction/dashboard/active-projects' },
      { label: 'Site Progress', value: '64%', trend: '+9% this month', hash: '/construction/dashboard/site-progress' },
      { label: 'Material Cost', value: money(1860000), trend: '7% over plan', hash: '/construction/dashboard/material-cost' },
      { label: 'Pending Bills', value: money(742000), trend: '18 bills pending', hash: '/construction/dashboard/pending-bills' },
    ],
    trend: [
      { label: 'W1', total: 42 }, { label: 'W2', total: 48 }, { label: 'W3', total: 53 },
      { label: 'W4', total: 58 }, { label: 'W5', total: 64 },
    ],
    donut: { paid: 1240000, pending: 742000, overdue: 218000 },
    list: [
      { name: 'Metro Mall Fitout', total: 82 },
      { name: 'Lakeview Villas', total: 67 },
      { name: 'Warehouse Phase 2', total: 54 },
    ],
    secondary: [
      { label: 'BOQs open', value: 9, color: '#2563eb', bg: '#eff6ff' },
      { label: 'Work orders', value: 31, color: '#16a34a', bg: '#f0fdf4' },
      { label: 'Milestones due', value: 6, color: '#d97706', bg: '#fffbeb' },
      { label: 'RA bills', value: 11, color: '#7c3aed', bg: '#f5f3ff' },
    ],
    inventory: { total: 426, inStock: 338, lowStock: 64, outOfStock: 24 },
    score: { score: 71, growthPct: 5 },
  },
  ngo: {
    title: 'NGO Dashboard',
    subtitle: 'Monitor donations, campaigns, beneficiaries served, and volunteer activity.',
    primaryChartTitle: 'Donation Trend',
    donutTitle: 'Donation Status',
    listTitle: 'Campaign Impact',
    secondaryCardTitle: 'Volunteer Activity',
    inventoryTitle: 'Beneficiary Coverage',
    scoreTitle: 'Impact Score',
    metrics: [
      { label: 'Total Donations', value: money(965000), trend: '+18% this month', hash: '/ngo/dashboard/total-donations' },
      { label: 'Active Campaigns', value: '7', trend: '3 ending soon', hash: '/ngo/dashboard/active-campaigns' },
      { label: 'Beneficiaries Served', value: '1,284', trend: '+142 this month', hash: '/ngo/dashboard/beneficiaries-served' },
      { label: 'Volunteers', value: '86', trend: '23 active today', hash: '/ngo/dashboard/volunteers' },
    ],
    trend: [
      { label: 'Jan', total: 120000 }, { label: 'Feb', total: 158000 }, { label: 'Mar', total: 142000 },
      { label: 'Apr', total: 176000 }, { label: 'May', total: 212000 }, { label: 'Jun', total: 157000 },
    ],
    donut: { paid: 728000, pending: 182000, overdue: 55000 },
    list: [
      { name: 'Food support drive', total: 486 },
      { name: 'Education kits', total: 312 },
      { name: 'Health camp', total: 224 },
    ],
    secondary: [
      { label: 'Assignments', value: 34, color: '#2563eb', bg: '#eff6ff' },
      { label: 'Certificates', value: 19, color: '#16a34a', bg: '#f0fdf4' },
      { label: 'Field visits', value: 12, color: '#d97706', bg: '#fffbeb' },
      { label: 'Open tasks', value: 8, color: '#7c3aed', bg: '#f5f3ff' },
    ],
    inventory: { total: 1284, inStock: 1036, lowStock: 182, outOfStock: 66 },
    score: { score: 88, growthPct: 14 },
  },
  automobile: {
    title: 'Automobile Dashboard',
    subtitle: "Track today's job cards, service bay load, revenue, and pending deliveries.",
    primaryChartTitle: 'Job Card Trend',
    donutTitle: 'Service Revenue Split',
    listTitle: 'Vehicles In Service',
    secondaryCardTitle: 'Service Operations',
    inventoryTitle: 'Spare Parts Snapshot',
    scoreTitle: 'Workshop Health Score',
    metrics: [
      { label: "Today's Job Cards", value: '38', trend: '12 new this morning', hash: '/automobile/dashboard/job-cards' },
      { label: 'Vehicles In Service', value: '27', trend: '9 awaiting parts', hash: '/automobile/dashboard/vehicles-in-service' },
      { label: 'Revenue', value: money(318000), trend: '+11% vs yesterday', hash: '/automobile/dashboard/revenue' },
      { label: 'Pending Delivery', value: '14', trend: '5 ready for pickup', hash: '/automobile/dashboard/pending-delivery' },
    ],
    trend: [
      { label: 'Mon', total: 24 }, { label: 'Tue', total: 31 }, { label: 'Wed', total: 29 },
      { label: 'Thu', total: 34 }, { label: 'Fri', total: 38 }, { label: 'Sat', total: 42 },
    ],
    donut: { paid: 186000, pending: 96000, overdue: 36000 },
    list: [
      { name: 'General service', total: 11 },
      { name: 'Body repair', total: 7 },
      { name: 'Insurance claim', total: 5 },
    ],
    secondary: [
      { label: 'Technicians assigned', value: 18, color: '#2563eb', bg: '#eff6ff' },
      { label: 'Estimates pending', value: 9, color: '#d97706', bg: '#fffbeb' },
      { label: 'Road tests', value: 6, color: '#16a34a', bg: '#f0fdf4' },
      { label: 'Approval links sent', value: 13, color: '#7c3aed', bg: '#f5f3ff' },
    ],
    inventory: { total: 620, inStock: 514, lowStock: 72, outOfStock: 34 },
    score: { score: 79, growthPct: 8 },
  },
};

export function getCategoryDashboard(category) {
  return CATEGORY_DASHBOARDS[category] || null;
}
