import { Schema, model } from 'mongoose';

const productVariantSchema = new Schema({
  size:          { type: String, trim: true, default: '' },
  modelName:     { type: String, trim: true, default: '' },
  modelCode:     { type: String, trim: true, default: '' },
  processor:     { type: String, trim: true, default: '' },
  ram:           { type: String, trim: true, default: '' },
  storage:       { type: String, trim: true, default: '' },
  colour:        { type: String, trim: true, default: '' },
  type:          { type: String, trim: true, default: '' },
  material:      { type: String, trim: true, default: '' },
  pattern:       { type: String, trim: true, default: '' },
  quality:       { type: String, trim: true, default: '' },
  ageGroup:      { type: String, trim: true, default: '' },
  other:         { type: String, trim: true, default: '' },
  display:       { type: String, trim: true, default: '' },
  graphics:      { type: String, trim: true, default: '' },
  operatingSystem: { type: String, trim: true, default: '' },
  purchasePrice: { type: Number, default: 0, min: 0 },
  mrp:           { type: Number, default: 0, min: 0 },
  rate:          { type: Number, default: 0, min: 0 },
  barcode:       { type: String, trim: true, default: '' },
  stock:         { type: Number, default: 0, min: 0 },
  minStockLevel: { type: Number, default: 0, min: 0 },
}, { _id: true });

const bundleItemSchema = new Schema({
  productId:    { type: Schema.Types.ObjectId, ref: 'Product', default: null },
  productName:  { type: String, trim: true, default: '' },
  sku:          { type: String, trim: true, default: '' },
  qty:          { type: Number, default: 1, min: 0 },
  unitPrice:    { type: Number, default: 0, min: 0 },
  total:        { type: Number, default: 0, min: 0 },
}, { _id: true });

const packingSchema = new Schema({
  pack: { type: String, trim: true, default: '' },
  quantity: { type: Number, default: 0, min: 0 },
  barcode: { type: String, trim: true, default: '' },
}, { _id: true });

const priceListSchema = new Schema({
  name: { type: String, trim: true, default: '' },
  price: { type: Number, default: 0, min: 0 },
}, { _id: true });

const branchSettingSchema = new Schema({
  branch: { type: String, trim: true, default: '' },
  active: { type: Boolean, default: true },
  mrp: { type: Number, default: 0, min: 0 },
  sellingPrice: { type: Number, default: 0, min: 0 },
  stock: { type: Number, default: 0, min: 0 },
  salesAllowed: { type: Boolean, default: true },
  purchaseAllowed: { type: Boolean, default: true },
}, { _id: true });

const supplierMappingSchema = new Schema({
  supplier: { type: String, trim: true, default: '' },
  purchasePrice: { type: Number, default: 0, min: 0 },
  leadTimeDays: { type: Number, default: 0, min: 0 },
}, { _id: true });

const productSchema = new Schema({
  userId:        { type: Schema.Types.ObjectId, ref: 'AppUser', required: true, index: true },
  branch:        { type: String, trim: true, default: '', index: true },
  code:          { type: String, required: true, trim: true, uppercase: true },
  description:   { type: String, required: true, trim: true },
  shortName:     { type: String, trim: true, default: '' },
  aliasCode:     { type: String, trim: true, default: '' },
  productDescription: { type: String, default: '' },
  itemType:      { type: String, enum: ['Product', 'Service'], default: 'Product', index: true },
  productType:   { type: String, trim: true, default: 'Standard' },
  serviceType:   { type: String, trim: true, default: '' },
  estimatedTime: { type: String, trim: true, default: '' },
  technician:    { type: String, trim: true, default: '' },
  applicableFor: { type: String, trim: true, default: '' },
  deliverable:   { type: String, trim: true, default: '' },
  serviceMode:   { type: String, trim: true, default: '' },
  serviceArea:   { type: String, trim: true, default: '' },
  additionalCharges: { type: Number, default: 0, min: 0 },
  preferredDate: { type: Date, default: null },
  preferredTime: { type: String, trim: true, default: '' },
  specialInstructions: { type: String, default: '' },
  staffProfessional: { type: String, trim: true, default: '' },
  ageGroup:      { type: String, trim: true, default: '' },
  preparationNotes: { type: String, default: '' },
  requirementsFromCustomer: { type: String, default: '' },
  repeatableService: { type: String, trim: true, default: '' },
  afterServiceSupport: { type: String, trim: true, default: '' },
  coverageDetails: { type: String, default: '' },
  serviceWarranty: { type: Boolean, default: false },
  modelFamily:   { type: String, trim: true, default: '' },
  variantAttributes: { type: [String], default: [] },
  preparationType: { type: String, trim: true, default: 'Trade As Is' },
  hsn:           { type: String, trim: true, default: '' },
  unit:          { type: String, trim: true, default: 'Nos' },
  baseUnit:      { type: String, trim: true, default: 'Nos' },
  salesUnit:     { type: String, trim: true, default: 'Nos' },
  purchaseUnit:  { type: String, trim: true, default: 'Nos' },
  conversionQty: { type: Number, default: 1, min: 0 },
  conversionToUnit: { type: String, trim: true, default: 'Nos' },
  isWeighable:   { type: Boolean, default: false },
  sellBy:        { type: String, trim: true, default: 'Unit' },
  rate:          { type: Number, required: true, min: 0 },
  purchasePrice: { type: Number, default: 0, min: 0 },
  landingCost:   { type: Number, default: 0, min: 0 },
  mrp:           { type: Number, default: 0, min: 0 },
  minSellingPrice: { type: Number, default: 0, min: 0 },
  gstRate:       { type: Number, default: 18, enum: [0, 5, 12, 18, 28] },
  taxType:       { type: String, trim: true, default: 'Tax Exclusive' },
  category:      { type: String, trim: true, default: '' },
  subCategory:   { type: String, trim: true, default: '' },
  brand:         { type: String, trim: true, default: '' },
  imageUrl:      { type: String, trim: true, default: '' },
  itemGroup:     {
    type: String,
    enum: [
      'General', 'Textile', 'Electronics', 'Pharma', 'Books', 'Uniform', 'Perishable',
      'RawMaterial', 'FinishedGood', 'Material', 'Equipment', 'SparePart', 'DonatedGoods',
    ],
    default: 'General',
  },
  size:          { type: String, trim: true, default: '' },
  fabric:        { type: String, trim: true, default: '' },
  material:      { type: String, trim: true, default: '' },
  colour:        { type: String, trim: true, default: '' },
  type:          { type: String, trim: true, default: '' },
  gender:        { type: String, trim: true, default: '' },
  collection:    { type: String, trim: true, default: '' },
  pattern:       { type: String, trim: true, default: '' },
  modelNumber:   { type: String, trim: true, default: '' },
  warrantyPeriod: { type: String, trim: true, default: '' },
  warrantyType:  { type: String, trim: true, default: '' },
  serialNumber:  { type: String, trim: true, default: '' },
  processor:     { type: String, trim: true, default: '' },
  ram:           { type: String, trim: true, default: '' },
  storage:       { type: String, trim: true, default: '' },
  display:       { type: String, trim: true, default: '' },
  operatingSystem: { type: String, trim: true, default: '' },
  serialTracking: { type: Boolean, default: false },
  serialRequired: { type: Boolean, default: false },
  // Hospital — Pharma
  batchNumber:   { type: String, trim: true, default: '' },
  batchTracking: { type: Boolean, default: false },
  expiryDate:    { type: Date, default: null },
  expiryTracking: { type: Boolean, default: false },
  expiryRequired: { type: Boolean, default: false },
  shelfLifeMonths: { type: Number, default: 0, min: 0 },
  expiryAlertDays: { type: Number, default: 0, min: 0 },
  manufacturer:  { type: String, trim: true, default: '' },
  prescriptionRequired: { type: Boolean, default: false },
  // School — Books / Uniform
  author:        { type: String, trim: true, default: '' },
  publisher:     { type: String, trim: true, default: '' },
  classGrade:    { type: String, trim: true, default: '' },
  edition:       { type: String, trim: true, default: '' },
  // Hotel — F&B / Perishable
  storageType:   { type: String, trim: true, default: '' },
  // Manufacturing / Construction — Raw Material / Finished Good / Material
  batchLotNo:    { type: String, trim: true, default: '' },
  gradeSpec:     { type: String, trim: true, default: '' },
  supplier:      { type: String, trim: true, default: '' },
  unitWeight:    { type: String, trim: true, default: '' },
  // Automobile — Spare Part
  partNumber:    { type: String, trim: true, default: '' },
  compatibleModel: { type: String, trim: true, default: '' },
  // NGO — Donated Goods
  donorName:     { type: String, trim: true, default: '' },
  condition:     { type: String, trim: true, default: '' },
  barcodeType:   { type: String, trim: true, default: 'EAN-13' },
  upc:           { type: String, trim: true, default: '' },
  ean:           { type: String, trim: true, default: '' },
  manufacturerPartNumber: { type: String, trim: true, default: '' },
  trackInventory: { type: Boolean, default: true },
  stock:         { type: Number, default: 0, min: 0 },
  openingStockValue: { type: Number, default: 0, min: 0 },
  reorderLevel:  { type: Number, default: 0, min: 0 },
  minStockLevel: { type: Number, default: 0, min: 0 },
  maxStockLevel: { type: Number, default: 0, min: 0 },
  safetyStock:   { type: Number, default: 0, min: 0 },
  warehouse:     { type: String, trim: true, default: 'Main Warehouse' },
  variants:      { type: [productVariantSchema], default: [] },
  bundleItems:   { type: [bundleItemSchema], default: [] },
  bundleDiscountType: { type: String, trim: true, default: 'Percentage' },
  bundleDiscount: { type: Number, default: 0, min: 0 },
  packingRows:   { type: [packingSchema], default: [] },
  priceLists:    { type: [priceListSchema], default: [] },
  branchSettings: { type: [branchSettingSchema], default: [] },
  salesAllowed:  { type: Boolean, default: true },
  allowRateEdit: { type: Boolean, default: true },
  allowDiscount: { type: Boolean, default: true },
  maxDiscount:   { type: Number, default: 0, min: 0 },
  allowNegativeStock: { type: Boolean, default: false },
  salesReturnAllowed: { type: Boolean, default: true },
  transferOutAllowed: { type: Boolean, default: true },
  purchaseAllowed: { type: Boolean, default: true },
  preferredSupplier: { type: String, trim: true, default: '' },
  leadTimeDays:  { type: Number, default: 0, min: 0 },
  minOrderQty:   { type: Number, default: 0, min: 0 },
  maxOrderQty:   { type: Number, default: 0, min: 0 },
  supplierMappings: { type: [supplierMappingSchema], default: [] },
  barcode:       { type: String, trim: true, default: '' },
  status:        { type: String, enum: ['Active', 'Inactive'], default: 'Active' },
}, { timestamps: true });

productSchema.index({ userId: 1, code: 1 }, { unique: true });
productSchema.index({ userId: 1, barcode: 1 });
productSchema.index({ userId: 1, description: 1, hsn: 1 });

export const Product = model('Product', productSchema);
