export const documentConfigs = {
  invoice: {
    buttonText: 'Save Bill',
    dateLabel: 'Invoice Date',
    documentType: 'gst-invoice',
    icon: 'Receipt',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Bill To',
    prefix: 'INV',
    showDueDate: true,
    showGst: true,
    showPayment: true,
    title: 'Tax Invoice',
  },
  'bill-of-supply': {
    buttonText: 'Save Bill',
    dateLabel: 'Bill Date',
    documentType: 'bill-of-supply',
    icon: 'FileText',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Bill To',
    prefix: 'BOS',
    printTitle: 'Tax Invoice',
    showDueDate: true,
    showGst: false,
    showPayment: true,
    title: 'Bill of Supply',
  },
  quotation: {
    buttonText: 'Create Quotation',
    dateLabel: 'Quote Date',
    documentType: 'quotation',
    icon: 'ClipboardList',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Quote To',
    prefix: 'QTN',
    showGst: true,
    showPayment: false,
    showValidTill: true,
    title: 'Quotation',
  },
  proforma: {
    buttonText: 'Create Proforma Invoice',
    dateLabel: 'Invoice Date',
    documentType: 'proforma-invoice',
    icon: 'FileText',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Bill To',
    prefix: 'PFI',
    showDueDate: true,
    showGst: true,
    showPayment: false,
    title: 'Proforma Invoice',
  },
  'purchase-order': {
    buttonText: 'Create Purchase Order',
    dateLabel: 'PO Date',
    documentType: 'purchase-order',
    icon: 'ShoppingCart',
    partyNameLabel: 'Vendor / Supplier Name *',
    partyToLabel: 'Vendor',
    prefix: 'PO',
    showDeliveryAddress: true,
    showExpectedDelivery: true,
    showGst: true,
    showPayment: false,
    title: 'Purchase Order',
  },
  'purchase-entry': {
    buttonText: 'Save Purchase Entry',
    dateLabel: 'Vendor Invoice Date',
    documentType: 'purchase-entry',
    icon: 'FileCheck',
    partyNameLabel: 'Vendor / Supplier Name *',
    partyToLabel: 'Vendor',
    prefix: 'PE',
    showGst: true,
    showPayment: false,
    showPurchaseOrderLink: true,
    title: 'Purchase Entry',
  },
  'credit-note': {
    buttonText: 'Create Credit Note',
    dateLabel: 'Credit Note Date',
    documentType: 'credit-note',
    icon: 'FileMinus',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Bill To',
    prefix: 'CRN',
    reasonLabel: 'Reason for Credit',
    showGst: true,
    showOriginalRef: true,
    showPayment: true,
    title: 'Credit Note',
  },
  'debit-note': {
    buttonText: 'Create Debit Note',
    dateLabel: 'Debit Note Date',
    documentType: 'debit-note',
    icon: 'FilePlus',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Bill To',
    prefix: 'DBN',
    reasonLabel: 'Reason for Debit',
    showGst: true,
    showOriginalRef: true,
    showPayment: true,
    title: 'Debit Note',
  },
  'sales-return': {
    buttonText: 'Create Sales Return',
    dateLabel: 'Return Date',
    documentType: 'sales-return',
    icon: 'ArrowRightLeft',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Bill To',
    prefix: 'SR',
    reasonLabel: 'Reason for Return',
    showGst: true,
    showOriginalRef: true,
    showPayment: true,
    title: 'Sales Return',
  },
  'supplier-return': {
    buttonText: 'Create Supplier Return',
    dateLabel: 'Return Date',
    documentType: 'supplier-return',
    icon: 'ArrowRightLeft',
    partyNameLabel: 'Vendor / Supplier Name *',
    partyToLabel: 'Vendor',
    prefix: 'SPR',
    reasonLabel: 'Reason for Return',
    showGst: true,
    showOriginalRef: true,
    showPayment: false,
    title: 'Supplier Return',
  },
  'delivery-challan': {
    buttonText: 'Create Delivery Challan',
    dateLabel: 'Challan Date',
    documentType: 'delivery-challan',
    icon: 'Truck',
    partyNameLabel: 'Consignee / Company Name *',
    partyToLabel: 'Consignee',
    prefix: 'DC',
    showGst: false,
    showPayment: false,
    showTransport: true,
    title: 'Delivery Challan',
  },
  'e-invoice': {
    buttonText: 'Generate E-Invoice',
    dateLabel: 'Invoice Date',
    documentType: 'e-invoice',
    icon: 'Zap',
    partyNameLabel: 'Customer / Company Name *',
    partyToLabel: 'Bill To',
    prefix: 'EI',
    showDueDate: true,
    showGst: true,
    showIRN: true,
    showPayment: true,
    title: 'E-Invoice',
  },
  'e-way-bill': {
    buttonText: 'Generate E-Way Bill',
    dateLabel: 'Date',
    documentType: 'e-way-bill',
    icon: 'Route',
    partyNameLabel: 'Consignee / Company Name *',
    partyToLabel: 'Consignee',
    prefix: 'EWB',
    showEWayBillFields: true,
    showGst: true,
    showPayment: false,
    showTransport: true,
    title: 'E-Way Bill',
  },
  'pharmacy-bill': {
    buttonText: 'Save Pharmacy Bill',
    dateLabel: 'Bill Date',
    documentType: 'pharmacy-bill',
    icon: 'Pill',
    partyNameLabel: 'Patient Name *',
    partyToLabel: 'Patient',
    prefix: 'PHB',
    showDueDate: false,
    showGst: true,
    showPayment: true,
    title: 'Pharmacy Bill',
  },
};
